class Objects:
    class Cube:
        ...
    class Sphere:
        ...
    class Plane:
        ...
    class Prism:
        ...
    class Grid:
        ...
    class Tetrahedron:
        ...
    class Cone:
        ...
    class Torus:
        ...
    class Cylinder:
        ...